milo/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', HomeView.as_view()),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='list'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='detail'),
    path('create', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/update', views.UserEditView.as_view(), name='edit'),
    path('<int:pk>/delete', views.UserDeleteView.as_view(), name='delete'),
    path('csv', views.download_csv, name='csv'),
]

users/models.py
import random

from django.contrib.auth.models import AbstractUser
from django.db import models


def random_number():
    return random.randint(1, 100)


class CustomUser(AbstractUser):
    birthday = models.DateField(null=True)
    number = models.IntegerField(default=random_number)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'birthday', 'password1', 'password2',)
        widgets = {
            'birthday': forms.DateInput(attrs={'class': 'datepicker'}, format='%d/%m/%Y'),
        }

users/views.py
import csv

from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic

from .forms import CreateUserForm
from .templatetags.custom import bizzfuzz, age

User = get_user_model()


class UserListView(generic.ListView):
    model = User


class UserDetailView(generic.DetailView):
    model = User
    context_object_name = 'user'
    queryset = User.objects.all()


class UserCreateView(generic.CreateView):
    model = User
    form_class = CreateUserForm

    def get_success_url(self):
        return reverse('users:detail', args=(self.object.id,))


class UserEditView(generic.UpdateView):
    model = User
    template_name_suffix = '_update_form'
    form_class = CreateUserForm

    def get_success_url(self):
        return reverse('users:detail', args=(self.object.id,))


class UserDeleteView(generic.DeleteView):
    model = User
    context_object_name = 'user'

    def get_success_url(self):
        return reverse('users:list')


class HomeView(generic.RedirectView):
    pattern_name = 'users:list'


def download_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="UserList.csv"'
    users = User.objects.all()
    writer = csv.writer(response)
    writer.writerow(['Username', 'Birthday', 'Eligible', 'Random Number', 'BizzFuzz'])
    for user in users:
        writer.writerow([user.username, user.birthday.strftime("%d/%m/%Y"),
                         age(user.birthday), user.number, bizzfuzz(user.number)])
    return response

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Milo Test{% endblock %}</title>
    {% block css %}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    {% endblock %}
</head>

<body>
<main>

    <div class="container">
        <h1>{% block content_title %}Page{% endblock %}</h1>
        <div class="card-panel">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</main>

{% block javascript %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
{% endblock javascript %}
</body>
</html>

templates/users/customuser_confirm_delete.html
{% extends "base.html" %}
{% load materializecss %}

{% block content_title %}Delete {{ user }}{% endblock %}
{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ user }}"?</p>
        <input type="submit" class="btn" value="Confirm">
        <a href="{% url 'users:detail' object.pk %}" class="waves-effect waves-light btn blue">No</a>
    </form>
{% endblock %}

templates/users/customuser_detail.html
{% extends "base.html" %}
{% load custom %}

{% block content_title %}User detail{% endblock %}
{% block content %}
    <div class="row">
        <div class="input-field col s6">
            <input readonly value="{{ user.username }}" id="readonly_username" type="text"
                   class="">
            <label class="" for="readonly_username">Username:</label>
        </div>
        <div class="input-field col s6">
            <input readonly value="{{ user.birthday }}" id="readonly_birthday" type="text"
                   class="">
            <label class="" for="readonly_birthday">Birthday:</label>
        </div>
        <div class="input-field col s4">
            <input readonly value="{{ user.birthday | age }}" id="readonly_eligible" type="text"
                   class="">
            <label class="" for="readonly_eligible">Eligible: </label>
        </div>
        <div class="input-field col s4">
            <input readonly value="{{ user.number }}" id="readonly_number" type="text"
                   class="">
            <label class="" for="readonly_number">Random Number:</label>
        </div>
        <div class="input-field col s4">
            <input readonly value="{{ user.number | bizzfuzz }}" id="readonly_bizzfuzz" type="text"
                   class="">
            <label class="" for="readonly_bizzfuzz">BizzFuzz:</label>
        </div>
    </div>
    <a href="{% url 'users:list' %}" class="waves-effect waves-light btn green"><i class="material-icons left">arrow_back</i>Back</a>
    <a href="{% url 'users:edit' user.pk %}" class="waves-effect waves-light btn blue"><i class="material-icons left">edit</i>Edit</a>
    <a href="{% url 'users:delete' user.pk %}" class="waves-effect waves-light btn red"><i class="material-icons left">cancel</i>Delete</a>
{% endblock %}

templates/users/customuser_form.html
{% extends "base.html" %}
{% load materializecss %}

{% block content_title %}Add User{% endblock %}
{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form|materializecss }}
        <button type="submit" class="btn btn-success">Add User</button>
        <a href="{% url 'users:list' %}" class="waves-effect waves-light btn green"><i class="material-icons left">arrow_back</i>Back</a>
    </form>
{% endblock %}

templates/users/customuser_list.html
{% extends "base.html" %}
{% load custom %}
{% block content_title %}User list{% endblock %}

{% block content %}
    <a class="waves-effect waves-light btn green" href={% url 'users:create' %}>add</a>
    <a class="waves-effect waves-light btn blue" href={% url 'users:csv' %}>Download CSV</a>
    <table style="width:100%">
        <tr>
            <th>Username</th>
            <th>Birthday</th>
            <th>Eligible</th>
            <th>Random Number</th>
            <th>BizzFuzz</th>
        </tr>
        {% for user in object_list %}
            <tr>
                <td><a href="{% url 'users:detail' user.pk %}">{{ user.username }}</a></td>
                <td>{{ user.birthday }}</td>
                <td>{{ user.birthday | age }}</td>
                <td>{{ user.number }}</td>
                <td>{{ user.number | bizzfuzz }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/users/customuser_update_form.html
{% extends "base.html" %}

{% block content_title %}Update User{% endblock %}
{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Update User</button>
        <a href="{% url 'users:list' %}" class="waves-effect waves-light btn green"><i class="material-icons left">arrow_back</i>Back</a>
    </form>
{% endblock %}